apiVersion: V1
kind: Service
metadata:
  name: backend
spec:
  selector:
    label: second-app
  port:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/1
kind: Deployment
metadata:
  name: deployment-name
spec:
  replicas: 1
  selector:
    matchLabbel:
      app: second-app
      tier: backend
  template:
    metadata:
      label:
        app: second-app
        tier: backend
    spec:
      container:
      - name: second-node
        image: docker-hub-name/deployment-image:v1

